import type { EvidenceItem, InterviewProbe } from "../api/client";
import { EmptyState } from "./ui";

export default function InterviewProbes({
  probes,
  evidence,
  onJump,
}: {
  probes: InterviewProbe[];
  evidence: EvidenceItem[];
  onJump: (evidenceId: string) => void;
}) {
  if (!probes.length) {
    return (
      <EmptyState title="No interview questions">
        Interview probes are generated by the advisory LLM layer. Re-run with
        “Add AI explanation” enabled (needs a Groq key) to get evidence-tied
        questions here.
      </EmptyState>
    );
  }

  const byId = new Map(evidence.map((e) => [e.id, e]));

  return (
    <div className="flex flex-col gap-3">
      <p className="text-sm text-slate-400">
        Questions an honest author should be able to answer — each tied to a
        specific piece of evidence, so a live conversation can confirm authorship.
      </p>
      {probes.map((probe, i) => {
        const target = byId.get(probe.targets_evidence_id);
        return (
          <div key={i} className="card-tight animate-fade-up">
            <div className="flex items-start gap-3">
              <span className="mt-0.5 flex h-6 w-6 shrink-0 items-center justify-center rounded-full bg-sky-500/15 text-xs font-semibold text-sky-300">
                {i + 1}
              </span>
              <div className="flex-1">
                <p className="text-sm text-slate-100">{probe.question}</p>
                {target ? (
                  <button
                    onClick={() => onJump(target.id)}
                    className="mt-2 inline-flex items-center gap-1.5 rounded-md border border-slate-700 bg-slate-950/50 px-2 py-1 text-[11px] text-slate-300 hover:border-sky-500/50 hover:text-sky-200"
                    title="Jump to the evidence this probes"
                  >
                    <span className="text-slate-500">probes →</span>
                    <span className="max-w-xs truncate">{target.summary}</span>
                  </button>
                ) : (
                  <span className="mt-2 inline-block text-[11px] text-slate-600">
                    targets {probe.targets_evidence_id}
                  </span>
                )}
              </div>
            </div>
          </div>
        );
      })}
    </div>
  );
}
